/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universalinterfacegui;




/**
 *
 * @author administrator
 */
public class LotteryGameUniversalGUI extends javax.swing.JFrame {
    
    
 






    /**
     * Creates new form LotteryGameUniversalGUI
     */
    public LotteryGameUniversalGUI() {
        initComponents();
        
        //gray panal 101
        specializedGameInterfacePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        universalContentPanel = new javax.swing.JScrollPane();
        universalOutputConsole = new javax.swing.JTextField();
        standardButtonLeft = new javax.swing.JButton();
        StandardButtonRight = new javax.swing.JButton();
        specializedGameInterfacePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        universalContentPanel.setMaximumSize(new java.awt.Dimension(400, 300));
        universalContentPanel.setMinimumSize(new java.awt.Dimension(400, 300));

        universalOutputConsole.setText("Hey welcome to LotteryGame");
        universalOutputConsole.setMaximumSize(new java.awt.Dimension(603, 34059403));
        universalOutputConsole.setMinimumSize(new java.awt.Dimension(400, 300));
        universalOutputConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universalOutputConsoleActionPerformed(evt);
            }
        });
        universalContentPanel.setViewportView(universalOutputConsole);

        standardButtonLeft.setText("Start");
        standardButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardButtonLeftActionPerformed(evt);
            }
        });

        StandardButtonRight.setText("Set Button");

        javax.swing.GroupLayout specializedGameInterfacePanelLayout = new javax.swing.GroupLayout(specializedGameInterfacePanel);
        specializedGameInterfacePanel.setLayout(specializedGameInterfacePanelLayout);
        specializedGameInterfacePanelLayout.setHorizontalGroup(
            specializedGameInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        specializedGameInterfacePanelLayout.setVerticalGroup(
            specializedGameInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(universalContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(specializedGameInterfacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(standardButtonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(StandardButtonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(universalContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(specializedGameInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standardButtonLeft)
                    .addComponent(StandardButtonRight))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void standardButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardButtonLeftActionPerformed
        // TODO add your handling code here:
        universalOutputConsole.setText("The game is starting...Play it's your turn!");
specializedGameInterfacePanel.setBackground(new java.awt.Color(232, 232, 232));
//interface 101
specializedGameInterfacePanel.setVisible(true);
standardButtonLeft.setEnabled(false);
this.revalidate();
this.repaint();


        
        
    }//GEN-LAST:event_standardButtonLeftActionPerformed

  
   
    
    
    
    private void universalOutputConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universalOutputConsoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universalOutputConsoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotteryGameUniversalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotteryGameUniversalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StandardButtonRight;
    private javax.swing.JPanel specializedGameInterfacePanel;
    private javax.swing.JButton standardButtonLeft;
    private javax.swing.JScrollPane universalContentPanel;
    private javax.swing.JTextField universalOutputConsole;
    // End of variables declaration//GEN-END:variables
}
